version: "3.1"
services:

  nginx:
    image: nginx:latest
    container_name: espresso
    ports:
       - "80:80"
    volumes:
       - espresso_web:/static
       - espresso_uploads:/uploads  # for syncing with django source code
       - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    container_name: espresso-web
    hostname: espresso-web
    build: 
      context: src
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn espresso.wsgi -b 0.0.0.0:8000"
    image: gabbarsingh/obou-coffee:1.2
    volumes:
      - ./src:/code               
      - espresso_web:/static
      - espresso_uploads:/uploads    

    depends_on:
      - db
    environment:
        - DJANGO_PRODUCTION=1

  db:
    image: postgres:10-alpine
    container_name: espresso-db
    hostname: espresso-db
    volumes:
         - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: $pgadmin_pwd
      POSTGRES_DB: espresso

  admin:
    image: adminer
    container_name: espresso-db-client
    hostname: espresso-db-client
    depends_on:
      - db
    ports:
      - 8080:8080

volumes: 
  pgdata:
  espresso_web:
  espresso_uploads: