version: '3.1'
services :
  db:
    image: postgres:10-alpine
    container_name: espresso-db
    hostname: espresso-db
    ports:
      - "5432:5432"
    
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: $pgadmin_pwd
      POSTGRES_DB: espresso

  admin:
    image: adminer
    container_name: espresso-db-client
    hostname: espresso-db-client
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080