version: "3.1"
services:
  web:
    container_name: espresso-web
    hostname: espresso-web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    container_name: espresso-db
    hostname: espresso-db
    volumes:
         - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: $pgadmin_pwd
      POSTGRES_DB: espresso

  admin:
    image: adminer
    container_name: espresso-db-client
    hostname: espresso-db-client
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

volumes: 
  pgdata: