# Generated by Django 3.2 on 2021-04-28 01:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsignature.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beans_intake', '0002_auto_20210421_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenBeansIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture_content', models.FloatField(default=0.0)),
                ('intake_type', models.CharField(choices=[('S', 'Hulled, graded and sorted'), ('N', 'Hulled, graded NOT sorted')], max_length=1)),
                ('grade1_weight', models.FloatField(default=0.0)),
                ('grade2_weight', models.FloatField(default=0.0)),
                ('grade3_weight', models.FloatField(default=0.0)),
                ('grade_pb_weight', models.FloatField(default=0.0)),
                ('grade_fines_weight', models.FloatField(default=0.0)),
                ('resting_period', models.IntegerField()),
                ('supervisor_signature', jsignature.fields.JSignatureField(blank=True, null=True)),
                ('delivery_person_name', models.CharField(blank=True, max_length=60, null=True)),
                ('delivery_person_signature', jsignature.fields.JSignatureField(blank=True, null=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('signed_delivery_slip', models.FileField(upload_to='delivery-slips')),
                ('delivery_person_pic', models.FileField(upload_to='delivery-persons')),
                ('marker_placed', models.BooleanField(default=False)),
                ('intake_note', models.TextField(blank=True, null=True)),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beans_intake.employee')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beans_intake.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='GreenBeansIntakeFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_file', models.FileField(upload_to='green-beans-intake-files')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_beans_intake.greenbeansintake')),
            ],
        ),migrations.RunSQL(
           'ALTER SEQUENCE green_beans_intake_greenbeansintake_id_seq RESTART WITH 5000000;'
        )
    ]
