# Generated by Django 3.1.7 on 2021-03-20 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beans_intake', '0002_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownintake',
            name='lot_detail',
        ),
        migrations.AddField(
            model_name='ownintake',
            name='lot_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beans_intake.location'),
        ),
    ]
