# Generated by Django 3.1.7 on 2021-03-20 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beans_intake', '0003_auto_20210320_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownintake',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
