# Generated by Django 3.2 on 2021-05-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hull_grade', '0002_alter_hullgradeintake_partial_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='hullgradeintake',
            name='hulled_graded',
            field=models.BooleanField(default=False),
        ),
    ]
