# Generated by Django 3.2 on 2021-05-06 02:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beans_intake', '0003_alter_inventory_partial_bag_weight'),
        ('hull_grade', '0003_hullgradeintake_hulled_graded'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradedBeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kgs_grade_1', models.FloatField(blank=True, default=0.0, null=True)),
                ('kgs_grade_2', models.FloatField(blank=True, default=0.0, null=True)),
                ('kgs_grade_3', models.FloatField(blank=True, default=0.0, null=True)),
                ('kgs_grade_pb', models.FloatField(blank=True, default=0.0, null=True)),
                ('kgs_grade_fines', models.FloatField(blank=True, default=0.0, null=True)),
                ('kgs_grade_non_exp', models.FloatField(blank=True, default=0.0, null=True)),
                ('kgs_grade_trash', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('hull_grade_intake', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hull_grade.hullgradeintake')),
                ('supervisor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beans_intake.employee')),
            ],
        ),migrations.RunSQL(
           'ALTER SEQUENCE hull_grade_gradedbeans_id_seq RESTART WITH 9990000;'
        )
    ]
