# Generated by Django 3.2 on 2021-04-21 16:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsignature.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beans_intake', '0002_auto_20210421_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParchmentIntake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bags_count', models.IntegerField()),
                ('total_weight', models.IntegerField()),
                ('moisture_content', models.FloatField(default=0.0)),
                ('sample_result', models.FloatField(default=0)),
                ('resting_period', models.IntegerField()),
                ('supervisor_signature', jsignature.fields.JSignatureField(blank=True, null=True)),
                ('delivery_person_name', models.CharField(blank=True, max_length=60, null=True)),
                ('delivery_person_signature', jsignature.fields.JSignatureField(blank=True, null=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('signed_delivery_slip', models.FileField(upload_to='delivery-slips')),
                ('delivery_person_pic', models.FileField(upload_to='delivery-persons')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beans_intake.employee')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beans_intake.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ParchmentIntakeFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_file', models.FileField(upload_to='parchment-intake-files')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parchment_intake.parchmentintake')),
            ],
        ),migrations.RunSQL(
           'ALTER SEQUENCE parchment_intake_parchmentintake_id_seq RESTART WITH 7000000;'
        )
    ]
