# Generated by Django 3.2 on 2021-04-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parchment_intake', '0003_alter_parchmentintake_marker_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='parchmentintake',
            name='intake_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
