# Generated by Django 3.2 on 2021-05-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parchment_intake', '0004_parchmentintake_intake_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parchmentintake',
            name='total_weight',
            field=models.FloatField(),
        ),
    ]
