# Generated by Django 3.2 on 2021-05-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parchment_intake', '0005_alter_parchmentintake_total_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parchmentintake',
            name='total_bags_count',
            field=models.FloatField(),
        ),
    ]
