# Generated by Django 3.1.7 on 2021-03-23 22:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsignature.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_name', models.CharField(max_length=60)),
                ('box_count', models.IntegerField()),
                ('total_weight', models.IntegerField()),
                ('discarded_weight', models.IntegerField()),
                ('refloated_weight', models.IntegerField()),
                ('proof_file', models.CharField(max_length=500)),
                ('supervisor_signature', jsignature.fields.JSignatureField()),
                ('representative_name', models.CharField(max_length=60)),
                ('representative_signature', jsignature.fields.JSignatureField()),
                ('is_external', models.BooleanField(default=False)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Refloat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refloat_weight', models.IntegerField()),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('intake', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beans_intake.intake')),
            ],
        ),
        migrations.AddField(
            model_name='intake',
            name='lot_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beans_intake.location'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_weight', models.IntegerField()),
                ('is_second_float', models.BooleanField(default=False)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('intake', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beans_intake.intake')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beans_intake.location')),
            ],
        ),
        migrations.RunSQL(
           'ALTER SEQUENCE beans_intake_intake_id_seq RESTART WITH 1000000;'
        )
        ,migrations.RunSQL(
           'ALTER SEQUENCE beans_intake_location_id_seq RESTART WITH 4000000;'
        )
        ,migrations.RunSQL(
           'ALTER SEQUENCE beans_intake_batch_id_seq RESTART WITH 5000000;'
        )
        ,migrations.RunSQL(
           'ALTER SEQUENCE beans_intake_refloat_id_seq RESTART WITH 2000000;'
        )
    ]
