# Generated by Django 3.1.7 on 2021-04-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beans_intake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='is_floated',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
