# Generated by Django 3.1.7 on 2021-04-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beans_intake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='moisture_content',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
