# Generated by Django 3.1.7 on 2021-04-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beans_intake', '0002_auto_20210402_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='is_floated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
