# Generated by Django 3.2 on 2021-05-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beans_intake', '0002_auto_20210421_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='partial_bag_weight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
