# Generated by Django 3.2 on 2021-04-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beans_intake', '0002_alter_inventoryfiles_proof_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakefiles',
            name='proof_file',
            field=models.FileField(upload_to='intake-files/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
