# Generated by Django 3.1.7 on 2021-03-24 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beans_intake', '0002_auto_20210323_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('status_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.RunSQL(
           'ALTER SEQUENCE beans_intake_status_id_seq RESTART WITH 3000000;'
        ),
        migrations.AlterField(
            model_name='batch',
            name='intake',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='beans_intake.intake'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beans_intake.status'),
        ),
    ]
