# Generated by Django 3.2 on 2021-05-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beans_intake', '0003_alter_inventory_partial_bag_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='passed_float_box_count',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='total_box_count',
            field=models.FloatField(),
        ),
    ]
