# Generated by Django 3.1.7 on 2021-04-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beans_intake', '0003_auto_20210402_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='passed_float_box_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
