# Generated by Django 3.1.7 on 2021-03-28 20:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beans_intake', '0004_refloat_floated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('dob', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DryingBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dry_coffee_weight', models.IntegerField()),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beans_intake.batch')),
            ],
        )
        ,migrations.RunSQL(
           'ALTER SEQUENCE beans_intake_sorter_id_seq RESTART WITH 9000000;'
        )
        ,migrations.RunSQL(
           'ALTER SEQUENCE beans_intake_dryingbatch_id_seq RESTART WITH 3000000;'
        )
    ]
