# Generated by Django 3.2 on 2021-05-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beans_intake', '0004_auto_20210512_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='full_bags',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
