# Generated by Django 3.1.7 on 2021-04-02 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beans_intake', '0006_auto_20210402_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beans_intake.status'),
        ),
    ]
