# Generated by Django 3.1.7 on 2021-04-02 04:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beans_intake', '0007_intake_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker_placed', models.BooleanField(default=True)),
                ('is_active_status', models.BooleanField(default=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='intake',
            name='status',
        ),
        migrations.AlterField(
            model_name='dryingbatch',
            name='batch',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.AddField(
            model_name='intakedetails',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beans_intake.intake'),
        ),
        migrations.AddField(
            model_name='intakedetails',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beans_intake.status'),
        ),
    ]
