# Generated by Django 3.1.7 on 2021-04-05 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beans_intake', '0008_auto_20210402_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(max_length=500)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beans_intake.intake')),
            ],
        ),
    ]
