# Generated by Django 3.1.7 on 2021-04-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beans_intake', '0009_intakenotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
