# Generated by Django 3.1.7 on 2021-04-05 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beans_intake', '0010_auto_20210405_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intake',
            name='proof_file',
        ),
        migrations.CreateModel(
            name='IntakeFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beans_intake.intake')),
            ],
        ),
    ]
