name: Docker Image CI

on:
  push:
    branches: [ develop, master, feature/* ]
  pull_request:
    branches: [ develop, master ]

jobs:

  build:
    name: Build the web-app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Echo variable
        run: echo '${{github.ref}} -  ${{github.repository}}'
      
      - name: Build the Docker image
        working-directory: ./src
        run: docker build . --file Dockerfile --tag '${{github.repository}}:${{github.sha}}' --tag '${{github.repository}}:latest'
