name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build the web-app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{github.GITHUB_REPOSITORY}}:${{github.GITHUB_REF}}
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
        
      - name: Push the docker image to container registry
        run: docker push ${{github.GITHUB_REPOSITORY}}:${{github.GITHUB_REF}}
        
