name: Publish Docker image
on:
  push:
    branches: [ master ]
  
jobs:

  publish:
    name: Publish Docker image to Github Container Registry
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
     
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
        
      - name: Build and Push to GitHub Container
        uses: docker/build-push-action@v2
        with:
          context: ./src
          push: true
          tags: |
            ghcr.io/mickymots/obou-coffee:latest
            ghcr.io/mickymots/obou-coffee:1.0.0